In [ ]:
# A empresa precisa responder:

# Qual foi o faturamento total considerando apenas ordens finalizadas?

# Quanto cada cliente faturou?

# Quantas ordens finalizadas cada cliente realizou?

# Qual foi o ticket médio por cliente?

# Quanto cada cidade faturou?

# Qual cidade teve maior faturamento?

In [2]:
# criando dataframes
import pandas as pd

clientes = pd.read_csv('../data/clientes.csv')
ordens = pd.read_csv('../data/ordens_servico.csv')

display(clientes, ordens)

   id_cliente nome_cliente           cidade
0           1         João        São Paulo
1           2        Maria        São Paulo
2           3          Ana        Guarulhos
3           4       Carlos           Suzano
4           5        Pedro  Mogi das Cruzes
5           6      Juliana        Guarulhos

    id_os  id_cliente        servico  valor      status
0       1           1  Troca de Óleo    120  Finalizado
1       2           2    Alinhamento     80  Finalizado
2       3           1          Freio    350  Finalizado
3       4           4  Troca de Óleo    120    Pendente
4       5           2          Freio    300  Finalizado
5       6           3        Revisão    500  Finalizado
6       7           1        Revisão    500  Finalizado
7       8           4    Alinhamento     80  Finalizado
8       9           3          Freio    320    Pendente
9      10           2        Revisão    500  Finalizado
10     11           5        Bateria    450  Finalizado
11     12           6  Troca de Óleo    120  Finalizado
12     13           6          Freio    380  Finalizado
13     14           5        Bateria    420   Cancelado
14     15           3    Alinhamento     90  Finalizado

In [18]:
# unindo tabelas

df = clientes.merge(ordens, how='right', on='id_cliente')
display(df.head(4))

   id_cliente nome_cliente     cidade  id_os        servico  valor      status
0           1         João  São Paulo      1  Troca de Óleo    120  Finalizado
1           2        Maria  São Paulo      2    Alinhamento     80  Finalizado
2           1         João  São Paulo      3          Freio    350  Finalizado
3           4       Carlos     Suzano      4  Troca de Óleo    120    Pendente

In [20]:
# filtrando por status finalizado
df = df[df['status']=='Finalizado']
display(df.head(4))

   id_cliente nome_cliente     cidade  id_os        servico  valor      status
0           1         João  São Paulo      1  Troca de Óleo    120  Finalizado
1           2        Maria  São Paulo      2    Alinhamento     80  Finalizado
2           1         João  São Paulo      3          Freio    350  Finalizado
4           2        Maria  São Paulo      5          Freio    300  Finalizado

In [21]:
# Qual foi o faturamento total considerando apenas ordens finalizadas?
faturamento_total = df['valor'].sum()
display(faturamento_total)

np.int64(3470)

In [23]:
# Quanto cada cliente faturou?
faturamento_cliente = df.groupby('nome_cliente')['valor'].sum()
display(faturamento_cliente)

nome_cliente
Ana        590
Carlos      80
João       970
Juliana    500
Maria      880
Pedro      450
Name: valor, dtype: int64

In [24]:
# Quantas ordens finalizadas cada cliente realizou?
ordens_cliente = df.groupby('nome_cliente')['id_os'].count()
display(ordens_cliente)

nome_cliente
Ana        2
Carlos     1
João       3
Juliana    2
Maria      3
Pedro      1
Name: id_os, dtype: int64

In [26]:
# Qual foi o ticket médio por cliente?
media_cliente = df.groupby('nome_cliente')['valor'].mean().round(1)
display(media_cliente)

nome_cliente
Ana        295.0
Carlos      80.0
João       323.3
Juliana    250.0
Maria      293.3
Pedro      450.0
Name: valor, dtype: float64

In [27]:
# Quanto cada cidade faturou?
faturamento_cidade = df.groupby('cidade')['valor'].sum()
display(faturamento_cidade)

cidade
Guarulhos          1090
Mogi das Cruzes     450
Suzano               80
São Paulo          1850
Name: valor, dtype: int64

In [28]:
# Qual cidade teve maior faturamento?
top_cidade = faturamento_cidade.idxmax()
display(top_cidade)

'São Paulo'

In [36]:
cidade_cliente = df.groupby('nome_cliente')['cidade'].first()
display(cidade_cliente)

nome_cliente
Ana              Guarulhos
Carlos              Suzano
João             São Paulo
Juliana          Guarulhos
Maria            São Paulo
Pedro      Mogi das Cruzes
Name: cidade, dtype: str

In [33]:
id_cliente = df.groupby('nome_cliente')['id_cliente'].first()
display(id_cliente)

nome_cliente
Ana        3
Carlos     4
João       1
Juliana    6
Maria      2
Pedro      5
Name: id_cliente, dtype: int64

In [39]:
# criando relatorio
relatorio = pd.DataFrame({
    'id_cliente': id_cliente,
    'cidade': cidade_cliente,
    'faturamento_total': faturamento_cliente,
    'qtd_ordens': ordens_cliente,
    'ticket_medio': media_cliente
}).reset_index().sort_values('id_cliente')

display(relatorio)

,nome_cliente,id_cliente,cidade,faturamento_total,qtd_ordens,ticket_medio
2,João,1,São Paulo,970,3,323.3
4,Maria,2,São Paulo,880,3,293.3
0,Ana,3,Guarulhos,590,2,295.0
1,Carlos,4,Suzano,80,1,80.0
5,Pedro,5,Mogi das Cruzes,450,1,450.0
3,Juliana,6,Guarulhos,500,2,250.0

In [41]:
# exportando relatorio
relatorio.to_csv('../output/relatorio.csv')